<#
.SYNOPSIS
    Scaffold a complete agenic workspace from scratch.
.DESCRIPTION
    Runs the full setup pipeline:
    1. Create .agents directory
    2. Link skills via junction
    3. Generate agents.md
    4. Rebuild BOSS_INDEX.json
.PARAMETER WorkspaceRoot
    The root directory of the project to set up.
.PARAMETER SkillRepoPath
    The full path to the skill repository's .agents\skills folder.
.PARAMETER SkipIndexUpdate
    Skip rebuilding BOSS_INDEX.json (useful if the index is already current).
.EXAMPLE
    .\New-AgenicWorkspace.ps1 -WorkspaceRoot "C:\Projects\my-app" -SkillRepoPath "C:\skill-repo\.agents\skills"
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$WorkspaceRoot,

    [Parameter(Mandatory = $true)]
    [string]$SkillRepoPath,

    [switch]$SkipIndexUpdate
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$agentsDir = Join-Path -Path $WorkspaceRoot -ChildPath ".agents"
$agentsMdPath = Join-Path -Path $agentsDir -ChildPath "agents.md"
$junctionPath = Join-Path -Path $agentsDir -ChildPath "skills"

Write-Host "=== Agenic Workspace Setup ===" -ForegroundColor Cyan
Write-Host "Workspace: $WorkspaceRoot"
Write-Host "Skills at: $SkillRepoPath"
Write-Host ""

# Step 1: Create .agents directory
Write-Host "[1/4] Creating .agents directory..." -ForegroundColor Yellow
New-Item -ItemType Directory -Path $agentsDir -Force | Out-Null
Write-Host "  ✓ $agentsDir"

# Step 2: Link skills via junction
Write-Host "[2/4] Linking skills..." -ForegroundColor Yellow
& "$scriptDir\New-SkillsJunction.ps1" -WorkspaceRoot $WorkspaceRoot -SkillRepoPath $SkillRepoPath
Write-Host "  ✓ $junctionPath → $SkillRepoPath"

# Step 3: Generate agents.md
Write-Host "[3/4] Generating agents.md..." -ForegroundColor Yellow
$date = Get-Date -Format "yyyy-MM-dd"
$agentsMdContent = @"
# Agentic Workspace Configuration
# Generated by BOSS meta-orchestrator
# Last updated: $date

Skills are linked via junction at `.agents/skills/` → `$SkillRepoPath`

## How to Use

This workspace uses the **BOSS meta-orchestrator** — a low-token skill registry system. Do not enumerate or load skills into context unless needed.

### Workflow

1. **Guardrail check** — Can you solve the task with basic tools (file editing, terminal, conversation)? If yes, solve directly. No skill needed.

2. **Registry lookup** — If the task is complex, query `BOSS_INDEX.json` at `.agents/skills/boss/BOSS_INDEX.json`:
   - Extract 2-5 keywords from the task
   - Match against skill `tags` and `triggers` in the index
   - If a `PROJECT_INDEX.json` exists at `.agents/skills/PROJECT_INDEX.json`, merge it (project skills override on name conflict)

3. **Load only what you need** — For each matched skill:
   - Read only the YAML frontmatter and "When to Use" section of its `SKILL.md`
   - Load the full skill only if step-by-step instructions are required
   - Never load more than 3 skills at once unless the task genuinely requires it

4. **Record combinations** — After completing a significant task, record useful skill combinations in AIngram for cross-session persistence.

### Principles

- **Don't load, register** — Skills are indexed in compact JSON, not dumped into context
- **Match before load** — Keyword-based registry lookup loads only what you'll use
- **Index once, query often** — The registry is a single pre-built file
- **Fail fast on simple tasks** — If basic tools can do it, don't touch the registry
"@

Set-Content -Path $agentsMdPath -Value $agentsMdContent -Encoding UTF8
Write-Host "  ✓ $agentsMdPath"

# Step 4: Rebuild BOSS_INDEX.json
if (-not $SkipIndexUpdate) {
    Write-Host "[4/4] Rebuilding BOSS_INDEX.json..." -ForegroundColor Yellow
    $updateScript = Join-Path -Path $junctionPath -ChildPath "boss\update-index.ps1"
    if (Test-Path -Path $updateScript) {
        & $updateScript
        Write-Host "  ✓ BOSS_INDEX.json updated"
    } else {
        Write-Warning "update-index.ps1 not found at $updateScript — skipping index rebuild"
    }
} else {
    Write-Host "[4/4] Skipped (SkipIndexUpdate)" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "=== Setup complete! ===" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "  - Agents will discover skills via BOSS_INDEX.json"
Write-Host "  - Edit .agents/agents.md to customize agent behavior"
Write-Host "  - Run 'pwsh .agents/skills/boss/update-index.ps1' after adding new skills"
